manual tests added
BME-MIT-IET/iet-hf-2023-minek pull request #10
Opened 2023-05-22 20:48 UTC by LeventeFarkashazi

Further manual testing required.

2023-05-23 12:59 UTC, fogleins requested changes
A megjelölt néhány typo-t javítsd kérlek.
A sikeres tesztekhez nem kell beírni a teszt eredményét a sikertelenekhez hasonlóan? Vagy akkor a manuális tesztelést ismertető md-be be kéne írni, hogy azok a tesztek, amelyeknek nincs ismertetve az eredményük, azok sikeresek voltak, az elvárásnak megfelelően futottak le.

2023-05-23 12:59 UTC, fogleins commented on manual tests/ForgetAgentCraftingFromBag.md
> +Új ágens létrehozása, anyag, ágens tárolása virológusnál. A virológus sikeresen létrehozza a bénító ágenst, így a zsákjában lévő anyag mennyisége nullára csökken, a bénító ágenst pedig hozzáadódik a
"bénító ágens"-re javítsd majd (_bénító ágenst_ helyett)

2023-05-23 12:59 UTC, fogleins commented on manual tests/ForgetAgentCraftingFromBag.md
> +- Virológus 1.: Nem fertőzött semmilyen vírussal, egy üres mezőn áll. Rendelkezik a felejtő ágens genetikus kódjával, egy ráskával és egy lecraftolt felejtő ágenssel.
"ráska" -> táska

2023-05-23 12:59 UTC, fogleins commented on manual tests/LearnAlreadyKnownGeneticCode.md
> +4. Itt a megjelenő listából kiválasztja a "Interact with this field" opciót.
"kiválasztja a "Interact (...)" helyett _az_

2023-05-23 12:59 UTC, fogleins commented on manual tests/MoveToFieldWithChorea.md
> +- Virológus 1.: choreával vírussal fertőzött, egy a fertőzött mezővel szomszédos mezőn áll. A legördülő menüben a „Move here” menüpont nem jelenik meg.
itt nem "chorea vírussal fertőzött" mezőre lép?

2023-05-23 12:59 UTC, fogleins commented on manual tests/PickUpBagEquipment.md
> +4. Itt a megjelenő listából kiválasztja a "Interact with this field" opciót.
kiválasztja _az_ Interact (...) opciót

2023-05-23 12:59 UTC, fogleins commented on manual tests/StealNucleotidFromNotNumb.md
> +- Virológus 2.: Nem fertőzött semmilyen vírussal, egy üres mezőn áll. Virológus 1.-vel azonos mezőn tartózkodik. Rendelkezik tetszőleges mennyiségű nukleotiddal.
"Virológus 1.-vel" -> "Virológus 1-gyel"

2023-05-23 12:59 UTC, fogleins commented on manual tests/ThrowAgentOnMyselfWhileUsingGloveAndCape.md
> +Felszerelések viselkedésének tedztelése ágens kenése közben.
*tesztelése

2023-05-23 12:59 UTC, fogleins commented on manual tests/ThrowAgentWhileNumb.md
> +- Virológus 2.: Nem fertőzött semmilyen vírussal, egy üres mezőn áll. Virológus 1.-vel azonos mezőn tartózkodik. Nem rendelkezik semmilyen védőfelszereléssel.
Virológus 1.-vel -> 1-gyel

2023-05-23 12:59 UTC, fogleins commented on manual tests/ThrowAgentWhileNumb.md
> +- Virológus 2.: Nem fertőzött semmilyen vírussal, egy üres mezőn áll. Virológus 1.-vel azonos mezőn tartózkodik. Nem rendelkezik semmilyen védőfelszereléssel.
Virológus 1.-vel -> 1-gyel

2023-05-23 12:59 UTC, fogleins commented on manual tests/ThrowForgetAgent.md
> +- Virológus 2.: Nem fertőzött semmilyen vírussal, egy üres mezőn áll. Virológus 1.-vel azonos mezőn tartózkodik. Nem rendelkezik semmilyen védőfelszereléssel. Van már megtanult genetikai kódja.
Virológus 1.-vel -> 1-gyel

2023-05-23 12:59 UTC, fogleins commented on manual tests/ThrowForgetAgent.md
> +- Virológus 2.: Fertőzött a felejtő ágennsel vírussal, egy üres mezőn áll. Virológus 1.-vel azonos mezőn tartózkodik. Nem rendelkezik semmilyen védőfelszereléssel. Nem rendelkezik megtanult genetikai
ágennsel -> ágenssel?

2023-05-25 15:17 UTC, LeventeFarkashazi commented on manual tests/MoveToFieldWithChorea.md
> +- Virológus 1.: choreával vírussal fertőzött, egy a fertőzött mezővel szomszédos mezőn áll. A legördülő menüben a „Move here” menüpont nem jelenik meg.
Ohh de... Köszi! Itt kimaradt egy lépés leírása, illetve egy másik dolgot is félreírtam.

2023-05-25 16:08 UTC, merged